version: '3'

services:
  bitpreco-arbitrage:
    image: bitpreco-arbitrage:latest
    container_name: bitpreco-arbitrage
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /home/node/app
    volumes:
          - .:/home/node/app/
    env_file: .env
    restart: unless-stopped