version: '3'

services:
  bitpreco-arbitrage:
    image: bitpreco-arbitrage:latest
    container_name: bitpreco-arbitrage
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/app
    env_file: .env
    logging:
      driver: none
    restart: unless-stopped