version: '3'

services:
  bitpreco-arbitrage:
    image: bitpreco-arbitrage
    container_name: bitpreco-arbitrage
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: unless-stopped