version: '3'

services:
  bitpreco-arbitrage:
    image: bitpreco-arbitrage:latest
    container_name: bitpreco-arbitrage
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./bitPreco-trading-arbitrage:/home/node/app/
    env_file: .env
    restart: unless-stopped